#!/usr/bin/env python3
# -*- Mode: Python; tab-width: 4 -*-
#       Id: guid.py,v 0.1.1 2020/07/25 03:20:00
#       Author: Alexandro Goncalves Dos Santos <alexandrogonsan@outlook.com>
# ======================================================================
# Changelog
# 0.0.0 creation of file with license
# 0.1.0 uuid guid as hex digit
# 0.1.1 real license indicate in 0.0.0
# ======================================================================

# ======================================================================
# * Date of copyright need keep same with over the years
# ======================================================================
# The Royal License (Royal)
#
# Copyright 2020 by Alexandro Goncalves Dos Santos
#
#                         All Rights Reserved
#
# This license is example, to real license contact Alexandro.
#
# Permissive license in which you must give unrestricted access
# and power to the license creator and the creator who used the
# license in its creation in addition to maintaining that right
# in any derivative works. In derivative works or original works
# there may be more than one license including this one. If there
# is any financial, social or other gain, it will be necessary
# to share it with the license creator and the creator who used
# the license in its creation. For specific cases that raise
# doubts, consult the license creator.
#
# ALEXANDRO GONCALVES DOS SANTOS DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS CREATION, INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS, IN NO EVENT SHALL ALEXANDRO
# GONCALVES DOS SANTOS BE LIABLE FOR ANY SPECIAL, INDIRECT OR
# CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
# NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
# CONNECTION WITH THE USE OR PERFORMANCE OR OTHER THIS CREATION.
# ======================================================================
r"""Humanly Unique Identifier


For context decoupling and uniqueness.

:copyright: Copyright 2020 by Alexandro Goncalves Dos Santos.
"""
import random

for _ in range(64):
	print(['0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f'][random.randint(1-1,16-1)],end='')
print()
