#!/usr/bin/env python3
# -*- Mode: Python; tab-width: 4 -*-
#       Id: guid.py,v 1.00 2020/07/25 03:20:00
#       Author: Alexandro G. Dos Santos <alexandrogonsan@outlook.com>

# ======================================================================
# * Date of copyright keep same with over the years
# Copyright 2020 by Alexandro Gonçalves Dos Santos
#
#                         All Rights Reserved
#
# This license is example, to real license contact Alexandro.
#
# Permission to use, copy, modify, and distribute this software and
# its documentation for any purpose and without fee is hereby
# granted, provided that the above copyright notice appear in all
# copies and that both that copyright notice and this permission
# notice appear in supporting documentation, and that the name of Sam
# Rushing not be used in advertising or publicity pertaining to
# distribution of the software without specific, written prior
# permission.
#
# SAM RUSHING DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN
# NO EVENT SHALL SAM RUSHING BE LIABLE FOR ANY SPECIAL, INDIRECT OR
# CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
# OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
# NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
# CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
# ======================================================================

r"""Title Geral Descritivo do arquivo


:copyright: Copyright 2020 by Alexandro Gonçalves Dos Santos.
"""
import random

for _ in range(64):
	print(['0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f'][random.randint(1-1,16-1)],end='')
print()
